version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_web_dev
    command: uvicorn shared.infrastructure.ui.web.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
  db:
    image: postgres:13.13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=oasis_hub
      - POSTGRES_PASSWORD=123qweQWE
      - POSTGRES_DB=oasis_hub_db
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
  jupyter-notebook:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan
    environment:
      - JUPYTER_TOKEN=mi_token_secreto
